version: "3.9"

services:

  web:
    build: .
    ports:
        - 8080:80
        - 8081:443
    depends_on:
     - memcached

  memcached:
    image: memcached
    ports:
        - "11211:11211"
        